services:
  - type: web
    name: project-samarth-api
    env: python
    pythonVersion: 3.11
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: bash setup.sh
    startCommand: python -m uvicorn src.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: DATA_GOV_API_KEY
        sync: false
      - key: DATA_GOV_BASE_URL
        value: https://api.data.gov.in/resource/
      - key: ALLOWED_ORIGINS
        sync: false

